- src/main/java/cn/cerc/jmis/page/AppLoginPage.java
> Revert "登录记住密码，完成提交"

- src/main/java/cn/cerc/jmis/core/IFormFilter.java
- src/main/java/cn/cerc/jmis/core/StartForms.java
- src/main/java/cn/cerc/jmis/services/SvrFormTimeout.java
> 增加菜单启停拦截器接口

- src/main/java/cn/cerc/jmis/page/AppLoginPage.java
Reverts cn-cerc/summer-mis#126
> Revert "注释判断是否手机登录代码"

- src/main/java/cn/cerc/jmis/page/AppLoginPage.java
- src/main/java/cn/cerc/jui/phone/Block307.java
- src/main/java/cn/cerc/jui/phone/FrmPhoneSample.java
Merge pull request #120 from cn-cerc/hrj-add-Block307
增加Block307，用于
三行文字列表显示，右侧带导航栏箭头
> 提交不小心撤销提交的代码

- src/main/java/cn/cerc/jui/phone/PhonePage.java
Reverts cn-cerc/summer-mis#148
> Revert "页面添加meta属性"

- src/main/java/cn/cerc/jpage/fields/AbstractField.java
- src/main/java/cn/cerc/jpage/vcl/TextBox.java
> 将input的自动完成功能默认设置为off

- src/main/java/cn/cerc/jpage/fields/editor/ColumnEditor.java
请联动关闭 vine2015 resolve [#5101](https://github.com/mimrc/vine2015/issues/5101)
> 给可编辑输入框添加上灰色边框

- pom.xml
This reverts commit 84ae5d2b33cc3232081aac4ae363c4c61cf87154.
> Revert "升级支付宝的sdk"

- src/main/java/cn/cerc/jpage/fields/AbstractField.java
- src/main/java/cn/cerc/jpage/fields/DialogField.java
- src/main/java/cn/cerc/jpage/fields/TextAreaField.java
> 增加TextAreaField，用于支持备注等字段长文本显示和输入

- src/main/java/cn/cerc/jmis/services/SvrUserLogin.java
link to
---
summer-db [#43](https://github.com/cn-cerc/summer-db/pull/43)
> [fix]获取硬件设备码服务过滤掉MachineCode_为空的记录

- src/main/java/cn/cerc/jmis/core/StartForms.java
Reverts cn-cerc/summer-mis#217
> Revert "改进菜单访问，增加菜单是否已订购的判断"

- src/main/java/cn/cerc/jmis/core/ClientDevice.java
- src/main/java/cn/cerc/jmis/page/AppLoginPage.java
- src/main/java/cn/cerc/jmis/services/SvrUserLogin.java
- src/main/java/cn/cerc/jmis/tools/R.java
注意，更新后必须同时进行如下数据库变更：
ALTER TABLE CurrentUser ADD Language_ VARCHAR(10) NULL
> 更新多语言框架，将原来由后台配置决定语言类别，改为由前台设置决定

- src/main/java/cn/cerc/jui/phone/Block112.java
Reverts cn-cerc/summer-mis#232
> Revert "删除Block112不需要的调用方法"

- src/main/java/cn/cerc/jmis/services/SvrUserLogin.java
Reverts cn-cerc/summer-mis#262
> Revert "[refactor] 改进登录验证，密码输入错误次数超过规定次数，自动停用账号"

- src/main/java/cn/cerc/jmis/message/MessageQueue.java
https://github.com/mimrc/vine-task/pull/31
https://github.com/mimrc/vine-app/pull/8403
> [fix] 消息队列添加极光推送消息提示音

- src/main/java/cn/cerc/jmis/page/RedirectPage.java
示例
---
```java
new RedirectPage(this, "index").put("mobile", "18566767108").put("name", "github");
```
结果
---
```
index?mobile=18566767108&name=github
```
> 改进 RedirectPage 的功能，支持url追加参数

- src/main/java/cn/cerc/jbean/core/ServerConfig.java
- src/main/java/cn/cerc/jmis/page/AppLoginPage.java
- src/main/java/cn/cerc/jmis/services/SvrUserLogin.java
link to summer-db [#83](https://github.com/cn-cerc/summer-db/pull/83)
> 改进ServerCondig单例模式的调用方式

- src/main/java/cn/cerc/mis/core/StartFormDefault.java
- src/main/java/cn/cerc/mis/core/StartForms.java
Reverts cn-cerc/summer-mis#332
> Revert "自动释放并关闭hanle"

- src/main/java/cn/cerc/mis/page/AppLoginDefault.java
- src/main/java/cn/cerc/mis/services/SvrUserLogin.java
https://github.com/mimrc/vine-project/pull/9318
> 改进登录判断，去除密码为空进行验证判断

- src/main/java/SvrUserLogin/IUserLoginCheck.java
- src/main/java/cn/cerc/mis/page/AppLoginDefault.java
vine-project：https://github.com/mimrc/vine-project/pull/9361
diteng-taiwan：https://github.com/mimrc/diteng-taiwan/pull/120
> 改进登录验证，新增登录接口，由各项目实现登录方法

- src/main/java/cn/cerc/mis/core/AbstractJspPage.java
- src/main/java/cn/cerc/ui/core/UrlRecord.java
- src/main/java/cn/cerc/ui/parts/UIHeader.java
- src/main/java/cn/cerc/ui/parts/UISheetModule.java
- src/main/java/cn/cerc/ui/parts/UISheetUrl.java
1->给所有的菜单左上角链接都加上“开始”
2->把相关操作隐藏
@HuangRongjun
> 新增左侧菜单的组件（用于做出菜单的显示）
